/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kucko.zavrsnirad.view;

/**
 *
 * @author Filip
 */
public class ObjektFrame extends javax.swing.JFrame {

    /**
     * Creates new form ObjektFrame
     */
    public ObjektFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNoviObjekt = new javax.swing.JToggleButton();
        btnPostojeciObjekt = new javax.swing.JToggleButton();
        btnPovratak = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNoviObjekt.setText("Novi Objekt");
        btnNoviObjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviObjektActionPerformed(evt);
            }
        });

        btnPostojeciObjekt.setText("Postojeći objekt");
        btnPostojeciObjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostojeciObjektActionPerformed(evt);
            }
        });

        btnPovratak.setText("Povratak");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPostojeciObjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNoviObjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPovratak, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnNoviObjekt)
                .addGap(75, 75, 75)
                .addComponent(btnPostojeciObjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnPovratak)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        new Menu().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed

    private void btnNoviObjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviObjektActionPerformed
        new NoviObjektFrame().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_btnNoviObjektActionPerformed

    private void btnPostojeciObjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostojeciObjektActionPerformed
        new PostojeciObjektFrame().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_btnPostojeciObjektActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnNoviObjekt;
    private javax.swing.JToggleButton btnPostojeciObjekt;
    private javax.swing.JToggleButton btnPovratak;
    // End of variables declaration//GEN-END:variables
}
